# Generated by Django 5.0.6 on 2024-09-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_webapp', '0003_eventcategory_cpdlog_event_cpdlog_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='membership_status',
            field=models.CharField(default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_cpd_points',
            field=models.IntegerField(default=0),
        ),
    ]
