# Generated by Django 5.0.6 on 2024-09-11 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c_webapp', '0004_profile_membership_status_profile_total_cpd_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
    ]
