# Generated by Django 5.0.6 on 2024-09-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_webapp', '0007_event_end_time_event_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='poster',
            field=models.ImageField(default='KCSFA-DEFAULT-POSTER-LANDSCAPE.png', upload_to='events/posters/'),
        ),
    ]
